/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedLeaguesRouteImport } from './routes/_authed/leagues'
import { Route as AuthedLeaguesIndexRouteImport } from './routes/_authed/leagues.index'
import { Route as AuthedLeaguesLeagueIdRouteImport } from './routes/_authed/leagues.$leagueId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLeaguesRoute = AuthedLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeaguesIndexRoute = AuthedLeaguesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedLeaguesRoute,
} as any)
const AuthedLeaguesLeagueIdRoute = AuthedLeaguesLeagueIdRouteImport.update({
  id: '/$leagueId',
  path: '/$leagueId',
  getParentRoute: () => AuthedLeaguesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/leagues': typeof AuthedLeaguesRouteWithChildren
  '/leagues/$leagueId': typeof AuthedLeaguesLeagueIdRoute
  '/leagues/': typeof AuthedLeaguesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/leagues/$leagueId': typeof AuthedLeaguesLeagueIdRoute
  '/leagues': typeof AuthedLeaguesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/leagues': typeof AuthedLeaguesRouteWithChildren
  '/_authed/leagues/$leagueId': typeof AuthedLeaguesLeagueIdRoute
  '/_authed/leagues/': typeof AuthedLeaguesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/leagues'
    | '/leagues/$leagueId'
    | '/leagues/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/logout' | '/signup' | '/leagues/$leagueId' | '/leagues'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/leagues'
    | '/_authed/leagues/$leagueId'
    | '/_authed/leagues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/leagues': {
      id: '/_authed/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof AuthedLeaguesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leagues/': {
      id: '/_authed/leagues/'
      path: '/'
      fullPath: '/leagues/'
      preLoaderRoute: typeof AuthedLeaguesIndexRouteImport
      parentRoute: typeof AuthedLeaguesRoute
    }
    '/_authed/leagues/$leagueId': {
      id: '/_authed/leagues/$leagueId'
      path: '/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof AuthedLeaguesLeagueIdRouteImport
      parentRoute: typeof AuthedLeaguesRoute
    }
  }
}

interface AuthedLeaguesRouteChildren {
  AuthedLeaguesLeagueIdRoute: typeof AuthedLeaguesLeagueIdRoute
  AuthedLeaguesIndexRoute: typeof AuthedLeaguesIndexRoute
}

const AuthedLeaguesRouteChildren: AuthedLeaguesRouteChildren = {
  AuthedLeaguesLeagueIdRoute: AuthedLeaguesLeagueIdRoute,
  AuthedLeaguesIndexRoute: AuthedLeaguesIndexRoute,
}

const AuthedLeaguesRouteWithChildren = AuthedLeaguesRoute._addFileChildren(
  AuthedLeaguesRouteChildren,
)

interface AuthedRouteChildren {
  AuthedLeaguesRoute: typeof AuthedLeaguesRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedLeaguesRoute: AuthedLeaguesRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
