create table "nflweeklypicks"."weekly_matchups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "name" text not null,
    "short_name" text not null,
    "start_date" timestamp with time zone not null,
    "week" text not null,
    "season" text not null,
    "home_team_id" bigint not null,
    "away_team_id" bigint
);


alter table "nflweeklypicks"."weekly_matchups" enable row level security;

alter table "nflweeklypicks"."teams" add column "abbreviation" text not null;

alter table "nflweeklypicks"."teams" add column "slug" text not null;

CREATE UNIQUE INDEX weekly_matchups_pkey ON nflweeklypicks.weekly_matchups USING btree (id);

alter table "nflweeklypicks"."weekly_matchups" add constraint "weekly_matchups_pkey" PRIMARY KEY using index "weekly_matchups_pkey";

alter table "nflweeklypicks"."weekly_matchups" add constraint "weekly_matchups_away_team_id_fkey" FOREIGN KEY (away_team_id) REFERENCES nflweeklypicks.teams(id) not valid;

alter table "nflweeklypicks"."weekly_matchups" validate constraint "weekly_matchups_away_team_id_fkey";

alter table "nflweeklypicks"."weekly_matchups" add constraint "weekly_matchups_home_team_id_fkey" FOREIGN KEY (home_team_id) REFERENCES nflweeklypicks.teams(id) not valid;

alter table "nflweeklypicks"."weekly_matchups" validate constraint "weekly_matchups_home_team_id_fkey";

grant delete on table "nflweeklypicks"."weekly_matchups" to "anon";

grant insert on table "nflweeklypicks"."weekly_matchups" to "anon";

grant references on table "nflweeklypicks"."weekly_matchups" to "anon";

grant select on table "nflweeklypicks"."weekly_matchups" to "anon";

grant trigger on table "nflweeklypicks"."weekly_matchups" to "anon";

grant truncate on table "nflweeklypicks"."weekly_matchups" to "anon";

grant update on table "nflweeklypicks"."weekly_matchups" to "anon";

grant delete on table "nflweeklypicks"."weekly_matchups" to "authenticated";

grant insert on table "nflweeklypicks"."weekly_matchups" to "authenticated";

grant references on table "nflweeklypicks"."weekly_matchups" to "authenticated";

grant select on table "nflweeklypicks"."weekly_matchups" to "authenticated";

grant trigger on table "nflweeklypicks"."weekly_matchups" to "authenticated";

grant truncate on table "nflweeklypicks"."weekly_matchups" to "authenticated";

grant update on table "nflweeklypicks"."weekly_matchups" to "authenticated";

grant delete on table "nflweeklypicks"."weekly_matchups" to "service_role";

grant insert on table "nflweeklypicks"."weekly_matchups" to "service_role";

grant references on table "nflweeklypicks"."weekly_matchups" to "service_role";

grant select on table "nflweeklypicks"."weekly_matchups" to "service_role";

grant trigger on table "nflweeklypicks"."weekly_matchups" to "service_role";

grant truncate on table "nflweeklypicks"."weekly_matchups" to "service_role";

grant update on table "nflweeklypicks"."weekly_matchups" to "service_role";

grant delete on table "nflweeklypicks"."weekly_schedules" to "anon";

grant insert on table "nflweeklypicks"."weekly_schedules" to "anon";

grant references on table "nflweeklypicks"."weekly_schedules" to "anon";

grant select on table "nflweeklypicks"."weekly_schedules" to "anon";

grant trigger on table "nflweeklypicks"."weekly_schedules" to "anon";

grant truncate on table "nflweeklypicks"."weekly_schedules" to "anon";

grant update on table "nflweeklypicks"."weekly_schedules" to "anon";

grant delete on table "nflweeklypicks"."weekly_schedules" to "authenticated";

grant insert on table "nflweeklypicks"."weekly_schedules" to "authenticated";

grant references on table "nflweeklypicks"."weekly_schedules" to "authenticated";

grant select on table "nflweeklypicks"."weekly_schedules" to "authenticated";

grant trigger on table "nflweeklypicks"."weekly_schedules" to "authenticated";

grant truncate on table "nflweeklypicks"."weekly_schedules" to "authenticated";

grant update on table "nflweeklypicks"."weekly_schedules" to "authenticated";

grant delete on table "nflweeklypicks"."weekly_schedules" to "service_role";

grant insert on table "nflweeklypicks"."weekly_schedules" to "service_role";

grant references on table "nflweeklypicks"."weekly_schedules" to "service_role";

grant select on table "nflweeklypicks"."weekly_schedules" to "service_role";

grant trigger on table "nflweeklypicks"."weekly_schedules" to "service_role";

grant truncate on table "nflweeklypicks"."weekly_schedules" to "service_role";

grant update on table "nflweeklypicks"."weekly_schedules" to "service_role";

create policy "auth_users_read_only"
on "nflweeklypicks"."weekly_matchups"
as permissive
for select
to authenticated
using (true);


create policy "service_role_all_access"
on "nflweeklypicks"."weekly_matchups"
as permissive
for all
to service_role
using (true)
with check (true);



