create schema if not exists "nflweeklypicks";

create table "nflweeklypicks"."teams" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "external_id" bigint not null
);


alter table "nflweeklypicks"."teams" enable row level security;

CREATE UNIQUE INDEX teams_external_id_key ON nflweeklypicks.teams USING btree (external_id);

CREATE UNIQUE INDEX teams_name_key ON nflweeklypicks.teams USING btree (name);

CREATE UNIQUE INDEX teams_pkey ON nflweeklypicks.teams USING btree (id);

alter table "nflweeklypicks"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "nflweeklypicks"."teams" add constraint "teams_external_id_key" UNIQUE using index "teams_external_id_key";

alter table "nflweeklypicks"."teams" add constraint "teams_name_key" UNIQUE using index "teams_name_key";

create policy "Enable read access for all users"
on "nflweeklypicks"."teams"
as permissive
for select
to authenticated
using (true);



