create table "nflweeklypicks"."weekly_schedules" (
    "id" bigint generated by default as identity not null,
    "season_id" bigint not null,
    "value" text not null,
    "start_date" timestamp with time zone not null,
    "end_date" timestamp with time zone not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "nflweeklypicks"."weekly_schedules" enable row level security;

CREATE UNIQUE INDEX season_weeks_pkey ON nflweeklypicks.weekly_schedules USING btree (id);

alter table "nflweeklypicks"."weekly_schedules" add constraint "season_weeks_pkey" PRIMARY KEY using index "season_weeks_pkey";

alter table "nflweeklypicks"."weekly_schedules" add constraint "season_weeks_season_id_fkey" FOREIGN KEY (season_id) REFERENCES nflweeklypicks.seasons(id) not valid;

alter table "nflweeklypicks"."weekly_schedules" validate constraint "season_weeks_season_id_fkey";

create policy "auth_users_read_only"
on "nflweeklypicks"."weekly_schedules"
as permissive
for select
to authenticated
using (true);


create policy "service_role_all_access"
on "nflweeklypicks"."weekly_schedules"
as permissive
for all
to service_role
using (true)
with check (true);



