create table "nflweeklypicks"."seasons" (
    "id" bigint generated by default as identity not null,
    "year" text not null,
    "type" text not null,
    "start_date" timestamp with time zone not null,
    "end_date" timestamp with time zone not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "nflweeklypicks"."seasons" enable row level security;

CREATE UNIQUE INDEX seasons_pkey ON nflweeklypicks.seasons USING btree (id);

alter table "nflweeklypicks"."seasons" add constraint "seasons_pkey" PRIMARY KEY using index "seasons_pkey";


